name: Issue Management

on:
  pull_request_target:
    types: [opened, reopened]
  issues:
    types: [opened, labeled]

jobs: 
    handle-issue: 
      permissions: 
        issues: write
        contents: read
        pull-requests: write
      uses: tejugang/test-actions/.github/workflows/linked-issue-to-PR-management.yml@main
    handle-pr: 
      permissions: 
        issues: write
        contents: read
        pull-requests: write
      uses: tejugang/test-actions/.github/workflows/linked-issue-to-PR-management.yml@main
        
