name: Issue Management

on:
  pull_request_target:
    types: [opened, reopened]
  issues:
    types: [opened, labeled]

jobs: 
    issue-management: 
        uses: tejugang/test-actions/.github/workflows/issue-management.yml@main
